export const FETCH_CHARACTER = 'FETCH_CHARACTER';
export const PENDING_CHARACTER = 'PENDING_CHARACTER';
export const REJECT_CHARACTER = 'REJECT_CHARACTER';

export const FETCH_SINGLECHARACTER = 'FETCH_SINGLECHARACTER';
export const PENDING_SINGLECHARACTER = 'PENDING_SINGLECHARACTER';
export const REJECT_SINGLECHARACTER = 'REJECT_SINGLECHARACTER';
